#!/usr/bin/env bash
# 2015, s.andres@syseleven.de
# test sms handler behavior
#

export DEBUG='true'

echo "### all defaults ###"
echo '{"id":"c27f6bd5-e2ce-4dad-8e1e-1f00c171dd5b","client":{"name":"compute.local","address":"127.0.0.1","bind":"127.0.0.1","subscriptions":[],"safe_mode":false,"nodetype":"compute-dev","cloudname":"dev","version":"0.20.3","timestamp":1444396255},"check":{"command":"PATH=$PATH:/usr/lib/nagios/plugins/ check_procs -C nova-compute -c 1:2","interval":60,"subscribers":[],"standalone":true,"name":"nova-compute","issued":1444396267,"executed":1444396267,"duration":0.009,"output":"PROCS CRITICAL: 0 processes with command name 'nova-compute' | procs=0;;1:2;0;\n","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2"],"total_state_change":6},"occurrences":3,"action":"create","timestamp":1444396267}' | ./sms.rb

echo "### sms override to false ###"
echo '{"id":"c27f6bd5-e2ce-4dad-8e1e-1f00c171dd5b","client":{"name":"compute.local","address":"127.0.0.1","bind":"127.0.0.1","subscriptions":[],"safe_mode":false,"nodetype":"compute-dev","cloudname":"dev","version":"0.20.3","timestamp":1444396255},"check":{"command":"PATH=$PATH:/usr/lib/nagios/plugins/ check_procs -C nova-compute -c 1:2","interval":60,"subscribers":[],"standalone":true,"name":"nova-compute","issued":1444396267,"executed":1444396267,"duration":0.009,"sms":false,"output":"PROCS CRITICAL: 0 processes with command name 'nova-compute' | procs=0;;1:2;0;\n","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2"],"total_state_change":6},"occurrences":3,"action":"create","timestamp":1444396267}' | ./sms.rb

echo "### sms override to custom values ###"
echo '{"id":"c27f6bd5-e2ce-4dad-8e1e-1f00c171dd5b","client":{"name":"compute.local","address":"127.0.0.1","bind":"127.0.0.1","subscriptions":[],"safe_mode":false,"nodetype":"compute-dev","cloudname":"dev","version":"0.20.3","timestamp":1444396255},"check":{"command":"PATH=$PATH:/usr/lib/nagios/plugins/ check_procs -C nova-compute -c 1:2","interval":60,"subscribers":[],"standalone":true,"name":"nova-compute","issued":1444396267,"executed":1444396267,"duration":0.009,"sms":["0151xxx","customtarget"],"output":"PROCS CRITICAL: 0 processes with command name 'nova-compute' | procs=0;;1:2;0;\n","status":2,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2"],"total_state_change":6},"occurrences":3,"action":"create","timestamp":1444396267}' | ./sms.rb
